server:
  port: 9999
  tomcat:
    max-http-form-post-size: -1
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  mvc:
    path match:
      matching-strategy: ant_path_matcher


serviceUI:
  userPath: src/main/resources/users
  projectPath: /opt/project/
  maps:
    mc:
      port: 25565
      command: "/opt/mc/start.sh"
    alist:
      port: 5244
      command: "systemctl start alist"
    mysql:
      port: 3306
      command: "systemctl start mysql"
    nginx:
      port: 80
      command: "systemctl start nginx"

